### PR TITLE
Deploy docs to . (the doctr default is docs)

### PR DESCRIPTION
**Pull request by asmeurer**
You'll need to delete the `docs` directory from `gh-pages` manually.

### CODE REVIEW

**Comment by asmeurer** [comment]
Also, once this works, feel free to add this to https://drdoctr.github.io/doctr/#projects-using-doctr (if you want), and suggestsions/improvements to our docs are welcome too.

**Comment by ocefpaf** [comment]
> You'll need to delete the docs directory from gh-pages manually.

No problem. Will do it later.

> Also, once this works, feel free to add this to https://drdoctr.github.io/doctr/#projects-using-doctr (if you want), and suggestions/improvements to our docs are welcome too.

Will do.

**Comment by asmeurer** [comment]
[That looks better](https://github.com/pyoceans/seapy/commit/7a5d90520e7bd7d22c471755c3a3671e046c88d2).

**Comment by asmeurer** [comment]
Also remember to delete the old deploy key from your other script.

**Comment by ocefpaf** [comment]
> That looks better.

So easy... Wish I tried `doctr` sooner.

> Also remember to delete the old deploy key from your other script.

Done!

**Pull request merged**
