### PR TITLE
Try doctr

### PR DESCRIPTION
**Pull request by ocefpaf**
Let's see if this works...

### CODE REVIEW

**Comment by asmeurer** [comment]
It looks right. The only way to tell for sure is to merge.

**Comment by ocefpaf** [comment]
> It looks right. The only way to tell for sure is to merge.

I guess it worked! See https://github.com/pyoceans/seapy/commit/f234d4425bcca37619105d4a1ab033ff85f64ea3

Thanks @asmeurer!

**Comment by asmeurer** [comment]
Is that what you wanted? It deployed to https://pyoceans.github.io/seapy/docs/, not https://pyoceans.github.io/seapy/ (that's what was there from before).

**Comment by asmeurer** [comment]
It's because `--gh-pages-docs` defaults to `docs` (for historical purposes; we should probably change the default to `.`).

**Comment by asmeurer** [comment]
Fixed at https://github.com/pyoceans/seapy/pull/26

**Comment by ocefpaf** [comment]
Saw that in the docs. But yeah... I assumed the `default` was not `docs`. I agree that the `default` should be `.`  to match what `jekyll`, `mkdocs`, pelican, and many others do.

**Pull request merged**
